
BEGIN TRY
	BEGIN TRANSACTION ADD_MENU

		DECLARE 
			@PARENT_MENU_HOME NVARCHAR(50),
			@PARENT_MENU_REPORTS NVARCHAR(50),
			@PARENT_MENU_TOOLS NVARCHAR(50),
			@PARENT_MENU_ADMIN NVARCHAR(50),
			@PARENT_MENU_ACCOUNT NVARCHAR(50);

		SET @PARENT_MENU_HOME = 'HOME';
		SET @PARENT_MENU_REPORTS = 'REPORTS';
		SET @PARENT_MENU_TOOLS = 'TOOLS';
		SET @PARENT_MENU_ADMIN = 'ADMIN';
		SET @PARENT_MENU_ACCOUNT = 'ACCOUNT';

		--#START PARENT MENU INSERTION

		IF NOT EXISTS (SELECT TOP 1 1  FROM Menu WHERE [Key] = @PARENT_MENU_HOME)
		BEGIN
			INSERT INTO Menu ([Key], [Order], [Description])
			VALUES
			(@PARENT_MENU_HOME, 1, 'Home Page')
		END

		IF NOT EXISTS (SELECT TOP 1 1  FROM Menu WHERE [Key] = @PARENT_MENU_REPORTS)
		BEGIN
			INSERT INTO Menu ([Key], [Order], [Description])
			VALUES
			(@PARENT_MENU_REPORTS, 2, 'Reports')
		END

		IF NOT EXISTS (SELECT TOP 1 1  FROM Menu WHERE [Key] = @PARENT_MENU_TOOLS)
		BEGIN
			INSERT INTO Menu ([Key], [Order], [Description])
			VALUES
			(@PARENT_MENU_TOOLS, 3, 'Tools')
		END

		IF NOT EXISTS (SELECT TOP 1 1  FROM Menu WHERE [Key] = @PARENT_MENU_ADMIN)
		BEGIN
			INSERT INTO Menu ([Key], [Order], [Description])
			VALUES
			(@PARENT_MENU_ADMIN, 4, 'Administrative Options')
		END

		IF NOT EXISTS (SELECT TOP 1 1  FROM Menu WHERE [Key] = @PARENT_MENU_ACCOUNT)
		BEGIN
			INSERT INTO Menu ([Key], [Order], [Description])
			VALUES
			(@PARENT_MENU_ACCOUNT, 5, 'Account Setting')
		END

		--#END PARENT MENU INSERTION

		--#START CHILDREN MENU INSERTION

		----#ADMIN CHILDREN
		------USERS
		DECLARE @ADMIN_MENU_ID UNIQUEIDENTIFIER;
		SELECT @ADMIN_MENU_ID = Id FROM Menu WHERE [Key] = @PARENT_MENU_ADMIN;
		IF NOT EXISTS (SELECT TOP 1 1  FROM Menu WHERE [Key] = 'USERS')
		BEGIN
			INSERT INTO Menu ([Key], [Order], [Description], ParentId)
			VALUES
			('USERS', 1, 'Account Setting', @ADMIN_MENU_ID)
		END
		----#ADMIN CHILDREN

		----#TOOLS CHILDREN
		------PRIORITY ANNOUNCEMENT
		DECLARE @TOOLS_MENU_ID UNIQUEIDENTIFIER;
		SELECT @TOOLS_MENU_ID = Id FROM Menu WHERE [Key] = @PARENT_MENU_TOOLS;
		IF NOT EXISTS (SELECT TOP 1 1  FROM Menu WHERE [Key] = 'PRIORITY')
		BEGIN
			INSERT INTO Menu ([Key], [Order], [Description], ParentId)
			VALUES
			('PRIORITY', 1, 'Priority Announcement', @TOOLS_MENU_ID)
		END
		------BROADCAST COMMUNICATION
		IF NOT EXISTS (SELECT TOP 1 1  FROM Menu WHERE [Key] = 'BROADCAST_COMMUNICATION')
		BEGIN
			INSERT INTO Menu ([Key], [Order], [Description], ParentId)
			VALUES
			('BROADCAST_COMMUNICATION', 2, 'Broadcast communication', @TOOLS_MENU_ID)
		END
		----#TOOLS CHILDREN

		--#END CHILDREN MENU INSERTION

 	COMMIT TRANSACTION ADD_MENU
END TRY
BEGIN CATCH 
  IF (@@TRANCOUNT > 0)
   BEGIN
      ROLLBACK TRANSACTION ADD_MENU
	  PRINT 'ERROR'
   END 
END CATCH