
BEGIN TRY
	BEGIN TRANSACTION ADD_PERMISSION_TERMINAL_TILES

		DECLARE 
			@PARENT_PERMISSION_TERMINAL_TILES NVARCHAR(50);

		SET @PARENT_PERMISSION_TERMINAL_TILES = 'TERMINAL_TILES';

		--#START PARENT PERMISSION INSERTION

		IF NOT EXISTS (SELECT TOP 1 1  FROM Permission WHERE [Key] = @PARENT_PERMISSION_TERMINAL_TILES)
		BEGIN
			INSERT INTO Permission([Key], [Description])
			VALUES
			(@PARENT_PERMISSION_TERMINAL_TILES, 'Terminal information tiles, with rich texts')
		END
		--#END PARENT PERMISSION INSERTION

		--#START CHILDREN PERMISSION INSERTION

		------ADMIN ONLY
		DECLARE @PERMISSION_TERMINAL_TILES_ID UNIQUEIDENTIFIER;
		SELECT @PERMISSION_TERMINAL_TILES_ID = Id FROM Permission WHERE [Key] = @PARENT_PERMISSION_TERMINAL_TILES;
		IF NOT EXISTS (SELECT TOP 1 1  FROM Permission WHERE [Key] = 'ADMIN_ONLY')
		BEGIN
			INSERT INTO Permission([Key], [Description], ParentId)
			VALUES
			('ADMIN_ONLY', 'Used to control the access to fields that must be used by Admins only', @PERMISSION_TERMINAL_TILES_ID)
		END
		----#ADMIN ONLY

		--#END CHILDREN PERMISSION INSERTION

 	COMMIT TRANSACTION ADD_PERMISSION_TERMINAL_TILES
END TRY
BEGIN CATCH 
  IF (@@TRANCOUNT > 0)
   BEGIN
      ROLLBACK TRANSACTION ADD_PERMISSION_TERMINAL_TILES
	  PRINT 'ERROR'
   END 
END CATCH