-- ADD THE MENUS AVAILABLE FOR THE ROLE 'SysAdmin'
BEGIN TRY
	BEGIN TRANSACTION ADD_MENU_ROLE_TYPE_RELATION

		DECLARE 
			@ROLE_SYS_ADMIN UNIQUEIDENTIFIER;

		DECLARE @MENUS_TO_ADD TABLE (
			MenuId UNIQUEIDENTIFIER NOT NULL
		);

		---SET ROLE IDS
		SELECT @ROLE_SYS_ADMIN = Id FROM RoleType WHERE Name = 'SysAdmin';

		-- GET ALL THE MISING MENUS FOR THE ROLE. SINCE IT IS ADMIN ROLE, ALL THE MENUS SHOULD BE RELATED
		INSERT INTO @MENUS_TO_ADD (MenuId)
		SELECT M.Id FROM Menu M WHERE M.Id NOT IN
		(
			SELECT MRT.MenuId FROM MenuRoleType MRT WITH(NOLOCK)
			WHERE MRT.RoleTypeId = @ROLE_SYS_ADMIN			
		);
		-- FOR ALL MENUS NOT CREATED, INSERT
		IF EXISTS (SELECT TOP 1 1 FROM @MENUS_TO_ADD)
		BEGIN
			INSERT INTO MenuRoleType (MenuId, RoleTypeId, CreationTime)
			SELECT MenuId, @ROLE_SYS_ADMIN, GETDATE() FROM @MENUS_TO_ADD
		END


 	COMMIT TRANSACTION ADD_MENU_ROLE_TYPE_RELATION
END TRY
BEGIN CATCH 
  IF (@@TRANCOUNT > 0)
   BEGIN
      ROLLBACK TRANSACTION ADD_MENU_ROLE_TYPE_RELATION
	  PRINT 'ERROR'
   END 
END CATCH