-- ADD THE MENUS AVAILABLE FOR THE ROLE 'LaborUser'
BEGIN TRY
	BEGIN TRANSACTION ADD_MENU_ROLE_TYPE_RELATION

		DECLARE 
			@ROLE_LABOR_USER UNIQUEIDENTIFIER;

		DECLARE @LABOR_USER_MENUS_TO_ADD TABLE (
			MenuId UNIQUEIDENTIFIER NOT NULL
		);

		---SET ROLE IDS
		SELECT @ROLE_LABOR_USER = Id FROM RoleType WHERE Name = 'LaborUser';

		-- GET ALL THE MISING MENUS FOR THE ROLE. FOR DEFAULT, ONLY SOME MENUS WLL BE AVAILABLE
		INSERT INTO @LABOR_USER_MENUS_TO_ADD (MenuId)
		SELECT M.Id FROM Menu M 
			WHERE M.Id NOT IN
			(
				SELECT MRT.MenuId FROM MenuRoleType MRT WITH(NOLOCK)
				WHERE MRT.RoleTypeId = @ROLE_LABOR_USER			
			)
			AND M.[Key] IN ('REPORTS','HOME','ACCOUNT','TOOLS','PRIORITY');

		-- FOR ALL MENUS NOT CREATED, INSERT
		IF EXISTS (SELECT TOP 1 1 FROM @LABOR_USER_MENUS_TO_ADD)
		BEGIN
			INSERT INTO MenuRoleType (MenuId, RoleTypeId, CreationTime)
			SELECT MenuId, @ROLE_LABOR_USER, GETDATE() FROM @LABOR_USER_MENUS_TO_ADD
		END


 	COMMIT TRANSACTION ADD_MENU_ROLE_TYPE_RELATION
END TRY
BEGIN CATCH 
  IF (@@TRANCOUNT > 0)
   BEGIN
      ROLLBACK TRANSACTION ADD_MENU_ROLE_TYPE_RELATION
	  PRINT 'ERROR'
   END 
END CATCH